OBJS += ppc/cpu.o                                                       \
        ppc/float_dsp_init.o                                            \

OBJS-$(CONFIG_PIXELUTILS) += ppc/pixelutils_init.o

ALTIVEC-OBJS += ppc/float_dsp_altivec.o                                 \

ALTIVEC-OBJS-$(CONFIG_PIXELUTILS) += ppc/pixelutils_altivec.o
